# Generated by Django 3.2.6 on 2021-08-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giangvien',
            fields=[
                ('mscb', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='monhoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_mon_hoc', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='quantri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('mssv', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
