# Generated by Django 3.2 on 2021-11-11 22:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='phanquyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'quantri'), (2, 'giangvien'), (3, 'sinhvien'), (4, 'staff')], default=1, max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='giangvien',
            fields=[
                ('mscb', models.AutoField(primary_key=True, serialize=False)),
                ('gioitinh', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
                ('so_dien_thoai', models.IntegerField(null=True)),
                ('hocvan', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('perm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hocphan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_hoc_phan', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('id_giangvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='lop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_lop', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('mssv', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('gioitinh', models.BooleanField(default=True)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True)),
                ('so_dien_thoai', models.IntegerField(null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('id_lop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.lop')),
                ('perm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_lop'],
            },
        ),
        migrations.CreateModel(
            name='staff_att',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now_add=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('id_department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.lop')),
            ],
        ),
        migrations.CreateModel(
            name='staffDo_att',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdanh', models.BooleanField(default=False)),
                ('id_diemdanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.staff_att')),
                ('id_nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='quantri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('gioitinh', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[(1, 'school'), (2, 'company')], default=1, max_length=255)),
                ('perm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_content', models.TextField()),
                ('noti_title', models.CharField(blank=True, max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('id_giangvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.giangvien')),
                ('id_hocphan', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='system.hocphan')),
            ],
        ),
        migrations.AddField(
            model_name='hocphan',
            name='id_lop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='system.lop'),
        ),
        migrations.CreateModel(
            name='diemdanh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_diem_danh', models.DateField()),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now_add=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('id_hocphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att', to='system.hocphan')),
            ],
        ),
        migrations.CreateModel(
            name='attendance_out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdanh', models.BooleanField(default=False)),
                ('id_diemdanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.diemdanh')),
                ('id_sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_out', to='system.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdanh', models.BooleanField(default=False)),
                ('id_diemdanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.diemdanh')),
                ('id_sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attdata', to='system.sinhvien')),
            ],
        ),
    ]
