# Generated by Django 3.2.6 on 2021-08-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210821_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giangvien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='ho_ten',
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='quantri',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quantri',
            name='ho_ten',
        ),
        migrations.RemoveField(
            model_name='quantri',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='ho_ten',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='pwd',
        ),
    ]
