# Generated by Django 3.2 on 2021-11-11 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20211111_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffDo_att',
            new_name='staffDo_att_in',
        ),
        migrations.CreateModel(
            name='staffDo_att_out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdanh', models.BooleanField(default=False)),
                ('id_diemdanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.staff_att')),
                ('id_nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.sinhvien')),
            ],
        ),
    ]
