# Generated by Django 3.2.6 on 2021-08-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210821_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phanquyen',
            old_name='user',
            new_name='user_type',
        ),
    ]
