# Generated by Django 3.2 on 2021-11-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20211111_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdo_att_in',
            name='id_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
        migrations.AddField(
            model_name='staffdo_att_out',
            name='id_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
    ]
