# Generated by Django 3.2.6 on 2021-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_user_phanquyen_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='dia_chi',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='dia_chi',
            field=models.CharField(default='', max_length=255),
        ),
    ]
