# Generated by Django 3.2.6 on 2021-08-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210826_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='dia_chi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='dia_chi',
            field=models.TextField(),
        ),
    ]
