# Generated by Django 3.2 on 2021-11-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20211111_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdo_att_in',
            name='id_department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
        migrations.AlterField(
            model_name='staffdo_att_out',
            name='id_department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
    ]
