# Generated by Django 3.2 on 2021-11-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20211111_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_att',
            name='id_department',
        ),
    ]
