# Generated by Django 3.2.6 on 2021-08-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20210826_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giangvien',
            name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='quantri',
            name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='dia_chi',
        ),
    ]
