# Generated by Django 3.2 on 2021-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_staff_att_id_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='type_user',
            field=models.IntegerField(default='1', max_length=10),
        ),
    ]
