# Generated by Django 3.2.6 on 2021-08-28 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20210827_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='monhoc',
            new_name='lop',
        ),
        migrations.DeleteModel(
            name='danhsach',
        ),
        migrations.RenameField(
            model_name='lop',
            old_name='ten_mon_hoc',
            new_name='ten_lop',
        ),
        migrations.RemoveField(
            model_name='hocphan',
            name='id_monhoc',
        ),
        migrations.AddField(
            model_name='hocphan',
            name='id_lop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='id_lop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
    ]
