# Generated by Django 3.2.6 on 2021-08-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20210828_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='id_lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.lop'),
        ),
    ]
