# Generated by Django 3.2.6 on 2021-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_sinhvien_id_lop'),
    ]

    operations = [
        migrations.CreateModel(
            name='danhsach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
