# Generated by Django 3.2 on 2021-11-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_sinhvien_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='type_user',
        ),
    ]
