# Generated by Django 3.2 on 2021-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_sinhvien_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='id_giangvien',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='id_hocphan',
        ),
        migrations.DeleteModel(
            name='attendance_out',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
