# Generated by Django 3.2 on 2021-11-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20211114_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id_diemdanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attdetails', to='system.diemdanh'),
        ),
    ]
