# Generated by Django 3.2.6 on 2021-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_attendance_diemdanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemdanh',
            name='ngay_diem_danh',
            field=models.DateField(auto_now=True),
        ),
    ]
