# Generated by Django 3.2 on 2021-11-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_staff_event_staff_event_checkin_staff_event_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_event',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.lop'),
        ),
        migrations.AddField(
            model_name='staff_event_checkin',
            name='id_nhanvien',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='system.sinhvien'),
        ),
        migrations.AddField(
            model_name='staff_event_checkout',
            name='id_nhanvien',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='system.sinhvien'),
        ),
    ]
