# Generated by Django 3.2.6 on 2021-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_diemdanh_ngay_diem_danh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemdanh',
            name='ngay_diem_danh',
            field=models.DateField(),
        ),
    ]
