# Generated by Django 3.2 on 2021-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20211125_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_event_checkout',
            old_name='timecheckin',
            new_name='timecheckout',
        ),
        migrations.AlterField(
            model_name='staff_event_checkin',
            name='timecheckin',
            field=models.DateField(auto_now_add=True),
        ),
    ]
