# Generated by Django 3.2 on 2021-11-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20211125_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_event',
            name='id_diemdanh',
        ),
    ]
