# Generated by Django 3.2.6 on 2021-09-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_diemdanh_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemdanh',
            name='status',
        ),
    ]
