# Generated by Django 3.2 on 2021-10-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_remove_diemdanh_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocphan',
            name='id_lop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='system.lop'),
        ),
    ]
