# Generated by Django 3.2 on 2021-11-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20211125_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_event',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
