# Generated by Django 3.2 on 2021-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_staff_event_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_event_checkin',
            name='timecheckin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff_event_checkout',
            name='timecheckout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
