# Generated by Django 3.2 on 2021-10-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_notifications_noti_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='ngay_tao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
