# Generated by Django 3.2 on 2021-11-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20211129_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('diemdanh', models.BooleanField(default=False)),
                ('id_diemdanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attdetailsout', to='system.diemdanh')),
                ('id_sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attdataout', to='system.sinhvien')),
            ],
        ),
    ]
