# Generated by Django 3.2 on 2021-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_notifications_ngay_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
