# Generated by Django 3.2 on 2021-11-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_attendance_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_event_checkin',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcheckin', to='system.staff_event'),
        ),
        migrations.AlterField(
            model_name='staff_event_checkout',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcheckout', to='system.staff_event'),
        ),
    ]
