# Generated by Django 3.2 on 2021-10-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_notifications_ngay_tao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='id_lop',
        ),
        migrations.AddField(
            model_name='notifications',
            name='id_hocphan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='system.hocphan'),
        ),
    ]
