# Generated by Django 3.2 on 2021-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20211021_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
