# Generated by Django 3.2 on 2021-10-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_notifications_ngay_cap_nhat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id_sinhvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attdata', to='system.sinhvien'),
        ),
    ]
