# Generated by Django 3.2 on 2021-12-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_alter_staff_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_event_checkin',
            name='id_nhanvien',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffcheckin', to='system.sinhvien'),
        ),
        migrations.AlterField(
            model_name='staff_event_checkout',
            name='id_nhanvien',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffcheckout', to='system.sinhvien'),
        ),
    ]
