# Generated by Django 3.2 on 2021-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_attendance_id_sinhvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='giangvien',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='hocvan',
            field=models.CharField(choices=[(1, 'Dai Hoc'), (2, 'Thac Si'), (3, 'Tien Si'), (4, 'Giao Su')], default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='so_dien_thoai',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='diachi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='so_dien_thoai',
            field=models.IntegerField(null=True),
        ),
    ]
