# Generated by Django 3.2 on 2021-12-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_auto_20211202_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_event',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_att', to='system.lop'),
        ),
    ]
