# Generated by Django 3.2 on 2021-10-26 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20211024_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='perm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
