# Generated by Django 3.2 on 2021-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_staff_event_id_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_event',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departmentatt', to='system.lop'),
        ),
    ]
