# Generated by Django 3.2 on 2021-12-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_quantri_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giangvien',
            name='tentochuc',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='tentochuc',
            field=models.CharField(default='', max_length=254),
        ),
    ]
