# Generated by Django 3.2 on 2021-12-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20211208_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='hocvan',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
